services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: directus
      POSTGRES_PASSWORD: directus
      POSTGRES_DB: directus
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  directus:
    build: ./directus
    env_file:
      - .env
    ports:
      - "8055:8055"
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - directus
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network: